main: com.weebly.openboxtechnologies.hnrbungee.hnrbungee
name: HnRBungeeCore
version: 0.1
author: TechnoBrony
description: HnRBungeeCore plugin
commands:
   templatecmd:
      description: This is a demo command.
      usage: /<command>